<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolicyAdmin.Application\PolicyAdmin.Application.csproj" />
    <ProjectReference Include="..\PolicyAdmin.Infrastructure\PolicyAdmin.Infrastructure.csproj" />
    <ProjectReference Include="..\PolicyAdmin.Persistence\PolicyAdmin.Persistence.csproj" />
    <ProjectReference Include="..\PolicyAdmin.Shared\PolicyAdmin.Shared.csproj" />
  </ItemGroup>

</Project>
